devices:
- name: k3
  port_match: XONE:K3:XONE:K3 MIDI 1
  learned_port_name: XONE:K3:XONE:K3 MIDI 1
  deck_target:
    type: Direct
    channel_to_deck:
      0: 0
      3: 3
      1: 1
      2: 2
  pad_mode_source: app
  shift:
    type: Note
    channel: 14
    note: 15
  mappings:
  - control:
      type: Note
      channel: 14
      note: 24
    action: deck.play
    physical_deck: 0
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 52
    action: deck.toggle_loop
    physical_deck: 0
    deck_index: null
    params: {}
    behavior: toggle
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 0
    action: deck.loop_size
    physical_deck: 0
    deck_index: null
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: null
    hardware_type: unknown
  - control:
      type: Note
      channel: 14
      note: 28
    action: deck.beat_jump_backward
    physical_deck: 0
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 32
    action: deck.beat_jump_forward
    physical_deck: 0
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 25
    action: deck.play
    physical_deck: 1
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 53
    action: deck.toggle_loop
    physical_deck: 1
    deck_index: null
    params: {}
    behavior: toggle
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 1
    action: deck.loop_size
    physical_deck: 1
    deck_index: null
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: null
    hardware_type: unknown
  - control:
      type: Note
      channel: 14
      note: 29
    action: deck.beat_jump_backward
    physical_deck: 1
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 33
    action: deck.beat_jump_forward
    physical_deck: 1
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 26
    action: deck.play
    physical_deck: 2
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 54
    action: deck.toggle_loop
    physical_deck: 2
    deck_index: null
    params: {}
    behavior: toggle
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 2
    action: deck.loop_size
    physical_deck: 2
    deck_index: null
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: null
    hardware_type: unknown
  - control:
      type: Note
      channel: 14
      note: 30
    action: deck.beat_jump_backward
    physical_deck: 2
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 34
    action: deck.beat_jump_forward
    physical_deck: 2
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 27
    action: deck.play
    physical_deck: 3
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 55
    action: deck.toggle_loop
    physical_deck: 3
    deck_index: null
    params: {}
    behavior: toggle
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 3
    action: deck.loop_size
    physical_deck: 3
    deck_index: null
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: null
    hardware_type: unknown
  - control:
      type: Note
      channel: 14
      note: 31
    action: deck.beat_jump_backward
    physical_deck: 3
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 35
    action: deck.beat_jump_forward
    physical_deck: 3
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 36
    action: deck.hot_cue_press
    physical_deck: 0
    deck_index: null
    params:
      slot: 0
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 37
    action: deck.hot_cue_press
    physical_deck: 1
    deck_index: null
    params:
      slot: 0
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 38
    action: deck.hot_cue_press
    physical_deck: 2
    deck_index: null
    params:
      slot: 0
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 39
    action: deck.hot_cue_press
    physical_deck: 3
    deck_index: null
    params:
      slot: 0
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 16
    action: mixer.volume
    physical_deck: null
    deck_index: 0
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 4
    action: mixer.eq_hi
    physical_deck: null
    deck_index: 0
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 8
    action: mixer.eq_mid
    physical_deck: null
    deck_index: 0
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 12
    action: mixer.eq_lo
    physical_deck: null
    deck_index: 0
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: Note
      channel: 14
      note: 40
    action: mixer.cue
    physical_deck: null
    deck_index: 0
    params: {}
    behavior: toggle
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 17
    action: mixer.volume
    physical_deck: null
    deck_index: 1
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 5
    action: mixer.eq_hi
    physical_deck: null
    deck_index: 1
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 9
    action: mixer.eq_mid
    physical_deck: null
    deck_index: 1
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: knob
  - control:
      type: ControlChange
      channel: 14
      cc: 13
    action: mixer.eq_lo
    physical_deck: null
    deck_index: 1
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: Note
      channel: 14
      note: 41
    action: mixer.cue
    physical_deck: null
    deck_index: 1
    params: {}
    behavior: toggle
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 18
    action: mixer.volume
    physical_deck: null
    deck_index: 2
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 6
    action: mixer.eq_hi
    physical_deck: null
    deck_index: 2
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 10
    action: mixer.eq_mid
    physical_deck: null
    deck_index: 2
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 14
    action: mixer.eq_lo
    physical_deck: null
    deck_index: 2
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: Note
      channel: 14
      note: 42
    action: mixer.cue
    physical_deck: null
    deck_index: 2
    params: {}
    behavior: toggle
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 19
    action: mixer.volume
    physical_deck: null
    deck_index: 3
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: ControlChange
      channel: 14
      cc: 7
    action: mixer.eq_hi
    physical_deck: null
    deck_index: 3
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: knob
  - control:
      type: ControlChange
      channel: 14
      cc: 11
    action: mixer.eq_mid
    physical_deck: null
    deck_index: 3
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: knob
  - control:
      type: ControlChange
      channel: 14
      cc: 15
    action: mixer.eq_lo
    physical_deck: null
    deck_index: 3
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: absolute
    hardware_type: fader
  - control:
      type: Note
      channel: 14
      note: 43
    action: mixer.cue
    physical_deck: null
    deck_index: 3
    params: {}
    behavior: toggle
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 20
    action: global.fx_scroll
    physical_deck: null
    deck_index: null
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: null
    hardware_type: unknown
  - control:
      type: Note
      channel: 14
      note: 13
    action: global.fx_select
    physical_deck: null
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: ControlChange
      channel: 14
      cc: 21
    action: browser.scroll
    physical_deck: null
    deck_index: null
    params: {}
    behavior: continuous
    shift_action: null
    encoder_mode: null
    hardware_type: unknown
  - control:
      type: Note
      channel: 14
      note: 14
    action: browser.select
    physical_deck: null
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 48
    action: deck.load_selected
    physical_deck: 0
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 49
    action: deck.load_selected
    physical_deck: 1
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 50
    action: deck.load_selected
    physical_deck: 2
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  - control:
      type: Note
      channel: 14
      note: 51
    action: deck.load_selected
    physical_deck: 3
    deck_index: null
    params: {}
    behavior: momentary
    shift_action: null
    encoder_mode: null
    hardware_type: button
  feedback:
  - state: deck.is_playing
    physical_deck: 0
    deck_index: null
    params: {}
    output:
      type: Note
      channel: 14
      note: 24
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.loop_active
    physical_deck: 0
    deck_index: null
    params: {}
    output:
      type: Note
      channel: 14
      note: 52
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.is_playing
    physical_deck: 1
    deck_index: null
    params: {}
    output:
      type: Note
      channel: 14
      note: 25
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.loop_active
    physical_deck: 1
    deck_index: null
    params: {}
    output:
      type: Note
      channel: 14
      note: 53
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.is_playing
    physical_deck: 2
    deck_index: null
    params: {}
    output:
      type: Note
      channel: 14
      note: 26
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.loop_active
    physical_deck: 2
    deck_index: null
    params: {}
    output:
      type: Note
      channel: 14
      note: 54
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.is_playing
    physical_deck: 3
    deck_index: null
    params: {}
    output:
      type: Note
      channel: 14
      note: 27
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.loop_active
    physical_deck: 3
    deck_index: null
    params: {}
    output:
      type: Note
      channel: 14
      note: 55
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.hot_cue_set
    physical_deck: 0
    deck_index: null
    params:
      slot: 0
    output:
      type: Note
      channel: 14
      note: 36
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.hot_cue_set
    physical_deck: 1
    deck_index: null
    params:
      slot: 0
    output:
      type: Note
      channel: 14
      note: 37
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.hot_cue_set
    physical_deck: 2
    deck_index: null
    params:
      slot: 0
    output:
      type: Note
      channel: 14
      note: 38
    on_value: 127
    off_value: 0
    layer: null
  - state: deck.hot_cue_set
    physical_deck: 3
    deck_index: null
    params:
      slot: 0
    output:
      type: Note
      channel: 14
      note: 39
    on_value: 127
    off_value: 0
    layer: null
  - state: mixer.cue_enabled
    physical_deck: null
    deck_index: 0
    params: {}
    output:
      type: Note
      channel: 14
      note: 40
    on_value: 127
    off_value: 0
    layer: null
  - state: mixer.cue_enabled
    physical_deck: null
    deck_index: 1
    params: {}
    output:
      type: Note
      channel: 14
      note: 41
    on_value: 127
    off_value: 0
    layer: null
  - state: mixer.cue_enabled
    physical_deck: null
    deck_index: 2
    params: {}
    output:
      type: Note
      channel: 14
      note: 42
    on_value: 127
    off_value: 0
    layer: null
  - state: mixer.cue_enabled
    physical_deck: null
    deck_index: 3
    params: {}
    output:
      type: Note
      channel: 14
      note: 43
    on_value: 127
    off_value: 0
    layer: null
