[package]
name = "mesh-core"
version.workspace = true
edition.workspace = true

[dependencies]
riff.workspace = true
signalsmith-stretch.workspace = true
libpd-rs.workspace = true
rayon = "1.10"
log = "0.4"
